[package]
name = "lol-record-analysis-tauri"
version = "1.5.6"
description = "A Tauri App"
authors = ["wnzzer"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "lol_record_analysis_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

regex = "1.10.3"
reqwest = { version = "0.11", features = ["json"] }
winapi = { version = "0.3.9", features = [
    "processthreadsapi",
    "handleapi",
    "tlhelp32",
    "psapi",
    "winbase",
    "minwindef",
    "ntdef",
    "libloaderapi",
    "memoryapi",
    "winnt"  # 添加 winnt 特性
] }
log = "0.4"
env_logger = "0.10"
base64 = "0.21"
